(expect (not (eq (to-i32 20260912) 20260912)) 'typed-equality-regression)
(expect (= (pack4 100 0 -100 99) 0xe31c80e4u32) 'pack-all-32-bits)
(expect (not (storage-load)) 'empty-storage)
(storage-reset)
(expect (= (buflen map-buf) 441) 'compact-map)
(expect (eq (car (trap (map-set-cell 20 20 1000))) 'exit-ok) 'map-is-writable)
(looprange i 0 map-cells (bufset-i8 map-buf i (- (mod i 201) 100)))
(setq thr-cfg-source 2)
(setq thr-cfg-invert 1)
(setq thr-cfg-min 90)
(setq thr-cfg-max 910)
(setq thr-cfg-deadband 50)
(setq thr-cfg-filter 125)
(setq thr-cfg-brake-mode 2)
(setq cfg-preset 0)
(expect (storage-save) 'first-save)
(define first-writes writes)
(expect (storage-save) 'unchanged-save)
(expect (= writes first-writes) 'unchanged-save-no-flash-writes)
(storage-reset)
(looprange i 0 map-cells (expect (in-range (storage-image-cell ee i) -100 100) (list 'bad-map-cell i (storage-image-cell ee i))))
(expect (storage-image-valid ee) 'stored-image-ranges)
(expect (storage-load) 'cold-reload)
(expect (and (= thr-cfg-source 2) (= thr-cfg-invert 1) (= thr-cfg-min 90)
             (= thr-cfg-max 910) (= thr-cfg-deadband 50) (= thr-cfg-filter 125)
             (= thr-cfg-brake-mode 2) (= cfg-preset 0)) 'config-roundtrip)
(expect (eq (type-of thr-cfg-filter) 'type-i) 'loaded-values-remain-fixnums)
(looprange i 0 map-cells (expect (= (bufget-i8 map-buf i) (- (mod i 201) 100)) 'map-roundtrip))
; Every slot must survive all signed-byte values, including byte 4 and tail.
(define old-cell (map-get-cell 0 0))
(bufset-i32 ee 60 0)
(expect (not (storage-load)) 'crc-rejects-corruption)
(expect (= (map-get-cell 0 0) old-cell) 'failed-load-keeps-live-map)
(expect (storage-save) 'repair-corrupt-save)
; Valid old images load and migrate on the next explicit save.
(bufset-i32 ee 0 20260912)
(expect (storage-load) 'legacy-load)
(expect (storage-save) 'legacy-migration)
(expect (= (eeprom-read-i 0) eeprom-magic) 'new-format-marker)
; Interruptions and false-success firmware returns never acknowledge success.
(looprange mode 0 3
    (progn
        (setq thr-cfg-min (+ 100 mode))
        (setq fail-addr 2)
        (setq fail-mode mode)
        (expect (not (storage-save)) 'write-failure-detected)
        (expect (not storage-busy) 'pause-cleared-after-error)
        (expect (not (storage-load)) 'partial-image-rejected)
        (setq fail-addr -1)
        (expect (storage-save) 'save-recovery)))
; Missing fields are rejected before any mutable state is changed.
(bufset-u8 ee-valid 3 0)
(expect (not (storage-load)) 'missing-slot)
(expect (storage-save) 'restore-slot)
(storage-reset)
(gen-thermal-map 1.0 0.0 0.02 0 1.0 0.02 0.0 0)
(expect (= (map-get-cell 10 20) 500) 'direct-electric-at-speed)
(expect (= (map-lookup 1000 1000) 1000) 'lookup-upper-bound)
(expect (= (map-lookup -50 1500) -20) 'lookup-clamps-inputs)
; Low alpha must settle at zero, not retain positive torque indefinitely.
(setq thr-cfg-min 0)
(setq thr-cfg-max 1000)
(setq thr-cfg-deadband 20)
(setq thr-cfg-filter 100)
(setq adc-value 1.0)
(looprange i 0 100 (thr-read))
(setq adc-value 0.0)
(looprange i 0 200 (thr-read))
(expect (= thr-filtered 0) 'ema-settles-to-zero)
(setq thr-cfg-invert 1)
(expect (= (thr-normalize 990) 0) 'inverted-deadband)
(setq thr-cfg-source 3)
(setq thr-test-value 800)
(setq thr-test-time clock-ms)
(setq thr-cfg-filter 1000)
(expect (= (thr-read) 800) 'bench-throttle)
(setq clock-ms (+ clock-ms 501))
(control-tick)
(expect (= motor-value 0.0) 'bench-watchdog)
(setq thr-cfg-source 1)
(setq ppm-age 0.6)
(setq adc-value 1.0)
(control-tick)
(expect (= motor-value 0.0) 'ppm-watchdog)
(uart-throttle-byte 0x33)
(uart-throttle-byte 0xA5)
(uart-throttle-byte 100)
(uart-throttle-byte (bitwise-xor 0xA5 100))
(expect (= uart-last-raw 500) 'uart-fragmented-frame)
(setq thr-cfg-source 0)
(setq thr-cfg-invert 0)
(setq thr-cfg-brake-mode 2)
(setq adc-value 0.5)
(setq adc-reads 0)
(control-tick)
(expect (= adc-reads 1) 'single-bidir-sample)
(expect brake-command 'negative-map-uses-brake-api)
; Malformed commands neither mutate state nor kill the receiver.
(define packet (array-create 3))
(bufset-u8 packet 0 0x03)
(handle-packet packet)
(expect (= last-status 6) 'short-packet-rejected)
(bufset-u8 packet 0 0x0A)
(bufset-i16 packet 1 0)
(handle-packet packet)
(expect (= last-status 0) 'receiver-survives-malformed-packet)
(expect (= thr-filtered 0) 'stop-clears-filter)
(define cfg (array-create 17))
(bufset-u8 cfg 0 3)
(bufset-u8 cfg 1 0)
(bufset-i16 cfg 2 1000)
(bufset-i16 cfg 4 0)
(bufset-i16 cfg 6 20)
(bufset-u8 cfg 8 0)
(bufset-i16 cfg 9 1000)
(bufset-i16 cfg 11 20)
(bufset-i16 cfg 13 0)
(bufset-u8 cfg 15 0)
(bufset-u8 cfg 16 1)
(handle-packet cfg)
(expect (= last-status 0) 'custom-config-accepted)
(expect (= (map-get-cell 10 20) 500) 'custom-config-regenerates)
(map-set-cell 10 20 770)
(bufset-u8 cfg 1 4)
(bufset-u8 cfg 16 0)
(handle-packet cfg)
(expect (= (map-get-cell 10 20) 770) 'import-preserves-map)
(bufset-i16 cfg 2 -1)
(handle-packet cfg)
(expect (= last-status 6) 'bad-config-rejected)
(expect (= cfg-torque-resp 1.0) 'bad-config-no-mutation)
(bufset-i16 cfg 2 1000)
(spawn-trap "event-stack-test" 256
    (lambda () (progn (handle-packet cfg) (send-cfg-echo) (send-full-map)
                      (expect (storage-save) 'event-stack-save))))
(recv ((exit-ok (? pid) (? value)) t) ((exit-error (? pid) (? value)) (exit-error value)))
(define telemetry-test (spawn-trap "telemetry-stack-test" 80 telemetry-loop))
(sleep 0.12)
(kill telemetry-test t)
(recv ((exit-ok (? pid) (? value)) t) ((exit-error (? pid) (? value)) (exit-error value)))
(spawn-trap "control-stack-test" 150 (lambda () (looprange n 0 10000 (control-tick))))
(recv ((exit-ok (? pid) (? value)) t) ((exit-error (? pid) (? value)) (exit-error value)))
(gc)
(check (list 'heap-used (lbm-heap-state 'get-num-alloc-cells) 'memory-free-words (mem-num-free)) t)
(check t)
