; Hardware boundary only is mocked; application functions run in real LispBM.
(define ee (array-create 512))
(define ee-valid (array-create 128))
(define writes 0)
(define fail-addr -1)
(define fail-mode 0)
(define clock-ms 1000)
(define adc-value 0.0)
(define ppm-age 0.0)
(define brake-value 0.0)
(define duty-value 0.0)
(define motor-value 0.0)
(define brake-command nil)
(define last-status 0)
(define last-command 0)
(define adc-reads 0)

(defun expect (ok label) (if ok t (exit-error label)))
(defun systime () clock-ms)
(defun secs-since (stamp) (/ (- clock-ms stamp) 1000.0))
(defun get-adc-decoded (channel) (if (= channel 0) adc-value brake-value))
(defun get-adc (channel) (progn (setq adc-reads (+ adc-reads 1)) adc-value))
(defun get-ppm () adc-value)
(defun get-ppm-age () ppm-age)
(defun get-duty () duty-value)
(defun get-rpm () 0.0)
(defun get-current () 0.0)
(defun conf-get (key) (if (eq key 'adc-v1-start) 0.5 3.0))
(defun set-current-rel (v) (progn (setq motor-value v) (setq brake-command nil)))
(defun set-brake-rel (v) (progn (setq motor-value v) (setq brake-command t)))
(defun send-data (b)
    (if (= (bufget-u8 b 0) 0x82)
        (progn (setq last-status (bufget-u8 b 1)) (setq last-command (bufget-u8 b 2)))))
(defun uart-start (baud) t)
(defun uart-read (buffer count offset stop timeout) 0)
(defun eeprom-read-i (addr)
    (if (= (bufget-u8 ee-valid addr) 1) (to-i32 (bufget-u32 ee (* addr 4))) nil))
(defun eeprom-store-i (addr value)
    (progn
        (expect storage-busy 'write-without-pause)
        (setq writes (+ writes 1))
        (if (= addr fail-addr)
            (cond ((= fail-mode 0) t)
                  ((= fail-mode 1) nil)
                  (t (exit-error 'injected-write-error)))
            (progn (bufset-i32 ee (* addr 4) value) (bufset-u8 ee-valid addr 1) t))))
; Same polynomial and initial value as the VESC crc16 extension.
(defun crc16 (b)
    (let ((crc 0))
        (progn
            (looprange i 0 (buflen b)
                (progn
                    (setq crc (bitwise-xor crc (shl (bufget-u8 b i) 8)))
                    (looprange bit 0 8
                        (setq crc (bitwise-and 0xffff
                            (if (> (bitwise-and crc 0x8000) 0)
                                (bitwise-xor (shl crc 1) 0x1021) (shl crc 1)))))))
            crc)))
